### ISSUE TITLE
Associate with Wahoo?

### ISSUE THREAD

**Issue by bucaran** [zmalltalker/fish-nuggets#16]
We are still relatively new in town, and just getting started, but we are more stable than the other options, namely OMF. I think some of these functions could be turned into a handful of Wahoo plugins or maybe some could be even make it to core. We are always accepting feature request and feedback. I would love if you could give [Wahoo](https://github.com/fish-shell/wahoo/blob/master/FAQ.md) a look.

Regards :smile:

**Comment by SonYBell** [comment]
:+1:

**Comment by bucaran** [comment]
@SonYBell Wahoo was merged with OMF and while the project is still alive I am now working on a different shell manager now.
