### ISSUE TITLE
`fg` function overrides built-in `fg` behavior.

### ISSUE THREAD

**Issue by deanmarano** [zmalltalker/fish-nuggets#18]
There was some cool stuff in `fish-nuggets` I wanted to try out, but this broke my workflow and I couldn't figure out how to not pull this in.

I use `bg`, `fg`, and Ctrl-Z a lot.
https://www.thegeekdiary.com/understanding-the-job-control-commands-in-linux-bg-fg-and-ctrlz/

Which conflicts with this function:
https://github.com/zmalltalker/fish-nuggets/blob/84822afd9549bcba4a5f4ee5c82001670196b322/functions/fg.fish#L2

Could this be renamed or somehow made optional?

**Comment by zmalltalker** [comment]
@deanmarano Thanks a lot, I didn't even realize this existed. I renamed the `fg` command to `fgr`, had no intention of breaking your workflow :-)

**Comment by deanmarano** [comment]
Thanks so much! I'm excited to dig into everything you've collected here :)
